/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerBindings worker/env.d.ts` (hash: ca7fbfd279372bc6774368c3b7d51aa7)
interface __BaseEnv_WorkerBindings {
  DB: D1Database
  ASSETS: Fetcher
  CLERK_PUBLISHABLE_KEY: string
  CLERK_SECRET_KEY: string
  CLERK_AUTHORIZED_PARTIES: string
  PROJECTS: DurableObjectNamespace<import('./index').ProjectStore>
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./index')
    durableNamespaces: 'ProjectStore'
  }
  interface PreviewEnv {
    DB: D1Database
    ASSETS: Fetcher
    CLERK_PUBLISHABLE_KEY: string
    CLERK_SECRET_KEY: string
    CLERK_AUTHORIZED_PARTIES: string
    PROJECTS: DurableObjectNamespace<import('./index').ProjectStore>
  }
  interface ProductionEnv {
    DB: D1Database
    ASSETS: Fetcher
    CLERK_PUBLISHABLE_KEY: string
    CLERK_SECRET_KEY: string
    CLERK_AUTHORIZED_PARTIES: string
    PROJECTS: DurableObjectNamespace<import('./index').ProjectStore>
  }
  interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'CLERK_PUBLISHABLE_KEY' | 'CLERK_SECRET_KEY' | 'CLERK_AUTHORIZED_PARTIES'>
  > {}
}
